const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  color: state => state.app.color,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  name: state => state.user.username,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  avatar: state => state.user.avatar,
  addRoutes: state => state.permission.addRoutes,
  routeData: state => state.routes.routeData,
  roleList: state => state.role.roleList,
}
export default getters
